### PR TITLE
Svelte: Added support for multiple handle and cancel elements

### PR DESCRIPTION
**Pull request by sidharth-anand**
Allows the user to specify multiple children to cancel dragging, or picks up multiple children matching the given selector to cancel dragging against,

Example:
```
<div use:draggable={{cancel: ".nodrag"}}>
    <div id="a" class="nodrag"></div>
    <div id="b" class="nodrag"></div>
</div>
```

Previously, only `#a` would get dragging cancelled, while now dragging is cancelled on both `#a` & `#b`.

### CODE REVIEW

**Comment by PuruVJ** [comment]
Thanks for this!!

This has been on my radar for a while, only thing stopping me is that I don't want to ship multiple cancels without multiple handles, and I haven't had time to look at it. When I get around to multiple handles, I will merge ur PR

**Comment by sidharth-anand** [comment]
Hey! I've also added support for multiple handles with the latest commit

**Comment by PuruVJ** [comment]
LGTM! Merging. Thanks for this and your patience!

**Comment by PuruVJ** [comment]
Hi! It's released in 1.2.1

https://twitter.com/puruvjdev/status/1534517147304873984

**Pull request merged**
