### PR TITLE
Fixing snapping while scaled.

### PR DESCRIPTION
**Pull request by matrushka**
This should work like this:

1. Inverse scaling (by dividing by `inverseScale`).
2. Snap the value
3. Reapply scaling (by multiplying with `inverseScale`).

Although currently we apply `floor` before scaling, depending on the scale this messes up coordinates. I've removed flooring and added rounding while assigning translates.

I've also noticed tests are broken as well. I guess I'll try to bring them back later and maybe even propose some Github actions to run them on PRs.

### CODE REVIEW

**Comment by PuruVJ** [comment]
Good catch! I'll test and merge soon!

**Comment by PuruVJ** [comment]
If possible, could you create a little REPL showing this issue? Would make it easy for me to test :)

**Comment by matrushka** [comment]
@PuruVJ will try to put something to a codesandbox or so, but need some time :)

**Comment by matrushka** [comment]
@PuruVJ here's an example: https://stackblitz.com/edit/vitejs-vite-bkqiyw?file=src%2FApp.svelte

Try to drag the red box, you'd see that the coordinates are not moving by 50px but they are moving by 48px

**Comment by PuruVJ** [comment]
Tested! It's perfect, thanks!

**Pull request merged**
