### PR TITLE
@neodrag/react

### PR DESCRIPTION
**Pull request by PuruVJ**
New package: `@neodrag/react`. Wraps around `@neodrag/svelte`

Bundle size: 1.97kb min+brotli

usage:

```tsx
import { Draggable } from '@neodrag/react';

function App() {
	return (
		<Draggable onDragStart={(data) => console.log(data)}>
			<div>Hola</div>
		</Draggable>
	);
}
```

> Draggable wraps a div around the children passed to it. Looking for comments whether a div should be there or a `children-as-function` should pass the ref. 

Or, with hooks, more control

```tsx
import { useDraggable } from '@neodrag/react';
import { useRef } from 'react';

function App() {
	const divRef = useRef<HTMLDivElement>(null);
	useDraggable(divRef, { onDrag: console.log });

	return <div ref={divRef}>Hola</div>;
}
```

**ANY AND ALL FEEDBACK WELCOME IN COMMENTS**

EDIT: I won't be including the Draggable component atm, due to some unsurities about its nature. Will maybe do in future

### CODE REVIEW

**Comment by soulsam480** [comment]
Very cool !

**Comment by gavinfogel** [comment]
I think wrapping children with a div is more friendly for beginner React programmers than passing children-as-function

**Comment by PuruVJ** [comment]
@gavinfogel Agreed. Though I'm kind of thinking of not exposing a component at all. I want to go with the hook entirely. Easier for me and more consistent with @neodrag/svelte(being a plain vanilla action rather than a svelte component)

**Comment by gavinfogel** [comment]
@PuruVJ I like this approach and would also advocate for a hook. I think it gives the most flexibility, and is also un-opinionated (don't have to change component hierarchy). I think it would be important to include some opinions of recommended/sample usage in those documentation. A good example of this is [this](https://github.com/vercel/swr/blob/main/examples/axios-typescript/libs/useRequest.ts). SWR is flexible for fetching data, but a good way to use it is this hook they build on top of the useSWR hook.

**Comment by PuruVJ** [comment]
This looks interesting. Thanks!

**Pull request merged**
